[package]
name = "mq_decrafting_table"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
mimalloc = "0.1.43"
rustc-hash = "2.0.0"
serde = { version = "1.0.210", features = ["derive"]}
serde_json = "1.0.128"

[profile.release]
lto = true