name: Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * 3-4'

jobs:
  check:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # - name: Setup Debug Session
      #   uses: csexton/debugger-action@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: node action.js
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_TOKEN }}
          TOKEN123: ${{ secrets.TOKEN123 }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            mq_decrating_table-rs/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
